export const errorData = [
  "com.atlas.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)",
  "com.atlas.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)",
  "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)",
  "at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
  "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)",
  "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)",
  "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)",
  "at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:913)",
  "at javax.servlet.http.HttpServlet.service(HttpServlet.java:654)",
  "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
  "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)",
  "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)",
  "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)",
  "at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:913)",
  "at javax.servlet.http.HttpServlet.service(HttpServlet.java:654)",
  "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
  "com.atlas.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)",
  "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)",
  "at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
  "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)",
  "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)",
  "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)",
  "at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:913)",
  "at javax.servlet.http.HttpServlet.service(HttpServlet.java:654)",
  "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
  "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)",
  "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)",
  "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)",
  "at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:913)",
  "at javax.servlet.http.HttpServlet.service(HttpServlet.java:654)",
  "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
];
